# Generated by Django 3.0.8 on 2021-01-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('contributors', models.CharField(max_length=200)),
                ('iswc', models.CharField(max_length=50, unique=True)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShowDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.MusicModel')),
            ],
        ),
    ]
